version: "3.9"
services:
  node_app:
    container_name: convert_csv_file
    build: .
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - node_app
    ports:
      - 5050:5050
