version: '3.9'
services:
  node_app:
    # container_name: node_app
    build: .
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - node_app
    ports:
      - 3000:3000